# Generated by Django 5.0.6 on 2024-07-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notelist_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notelist',
        ),
    ]
